seed: 42
model_dir: ../../models/cfm_vc_me
resume_checkpoint: false

train:
  fp16: true
  batch_size: 32
  num_epochs: 3000
  save_interval: 1
  train_ratio: 0.9

data:
  data_dir: ./DATA

model:
  encoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    kernel_size: 7
    dropout: 0.1

  decoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    kernel_size: 7
    dropout: 0.1

optimizer:
  lr: 1.0
  betas: [0.9, 0.98]
