seed: 42
model_dir: ../../models/cfm_vc
resume_checkpoint: false

train:
  fp16: true
  batch_size: 32
  num_epochs: 1500
  log_interval: 100

data:
  data_dir: ./DATA

model:
  encoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    dropout: 0.1

  decoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    dropout: 0.1

optimizer:
  lr: 0.001
  betas: [0.8, 0.99]
